# Generated by Django 4.2 on 2023-04-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_clientes_delete_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='edad',
            new_name='telefono',
        ),
    ]
