# Generated by Django 4.2 on 2023-06-03 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_contraseña_clientes_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_de_realizacion',
            field=models.DateField(default='2023-05-31'),
            preserve_default=False,
        ),
    ]
