# Generated by Django 4.2 on 2023-06-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_clientes_descripcion_clientes_fecha_de_realizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='fecha_de_realizacion',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='telefono',
        ),
    ]
