# Generated by Django 4.2 on 2023-06-03 16:35

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_remove_clientes_descripcion_remove_clientes_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.CharField(default='ejemplo@gmail.com', max_length=25),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_de_realizacion',
            field=models.DateField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
