# Generated by Django 4.2 on 2023-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_clientes_descripcion_clientes_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha_de_realizacion',
            field=models.DateField(default='2023-06-03'),
        ),
    ]
