# Generated by Django 4.2 on 2023-06-03 16:43

from django.db import migrations, models
from django.utils import timezone   


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_clientes_fecha_de_realizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha_de_realizacion',
            field=models.DateField(default=timezone.now),
        ),
    ]
