# Generated by Django 4.2 on 2023-06-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_alter_clientes_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen_clientes/'),
        ),
    ]
