# Generated by Django 4.2 on 2023-06-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_clientes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='clientes/'),
        ),
    ]
