# Generated by Django 4.2 on 2023-06-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_infoextra_avatar_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='localidad',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
